name: Child Workflow

on:
  repository_dispatch:
    types: [start-child-workflow]

jobs:
  delete_files_and_create_folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Delete files job
      - name: Delete files
        run: |
          # Navigate to the specified folder
          cd data_new

          # Delete all files in the folder while keeping the folder itself
          rm -rf ./*

      # Create empty folder job
      - name: Create empty folder
        env:
          FOLDER_NAME: "data_new" # Default folder name
        run: |
          mkdir -p $FOLDER_NAME
          touch $FOLDER_NAME/.gitkeep

      # Commit changes job
      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "matze240"
          git config --global url.https://${{ secrets.other }}@github.com/.insteadOf https://github.com/
          git add -A
          git commit -m "Delete all files from specified folder and create empty folder $FOLDER_NAME"
          git push
